main="./worker/index.js"
name = "helium"
compatibility_flags = ["streams_enable_constructors"]
compatibility_date = "2021-09-17"
workers_dev = true
node_compat = true

[vars]
INSTANCE_NAME = "prod"

[site]
bucket = "./dist/client"

[dev]
port = 3000
