name: Run Test Suite

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    env:
      NODE_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install depdencies
        run: npm ci

      - name: Run Test Suite
        run: npm run test

      - name: Merge Staging->Main
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MESSAGE: "merge: {{sha}}"