name: Run Test Suite

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    env:
      NODE_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install depdencies
        run: npm ci

      - name: Run Test Suite
        run: npm run test

      - name: Merge Staging->Main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.respository }}.git
          git config --global user.email sre@thoughtindustries.com
          git config --global user.name ti-bot
          git fetch origin main
          git checkout main
          git merge staging --ff-only
          git push origin main