name: Run Test Suite

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    env:
      NODE_ENV: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install depdencies
        run: npm ci

      - name: Run Test Suite
        run: npm run test

      # actions bot email: https://github.community/t/github-actions-bot-email-address/17204/6    
      # lerna will mod package metadata and push to remote, so git user is needed
      - name: Merge Staging->Main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name GitHub Actions
          git fetch origin main
          git checkout main
          git merge staging --ff-only
          git push origin main