name: Publish Storybook Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      NODE_ENV: test

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install depdencies
        run: npm ci

      - name: Run Test Suite
        run: npm run test